sudo: false

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - cabal-install-1.22
    - ghc-7.10.1


install:
 - travis_retry cabal update
 - runhaskell BuildFromSource.hs build
 - cabal sandbox init --sandbox="`pwd`"/Elm-Platform/build/.cabal-sandbox
 - cabal install --only-dependencies --enable-tests


script:
 - cabal configure
 - cabal build
 - cabal install
 - ./tests/run-tests.sh
